services:
  staker-test-util:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: staker-test-util
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=DEBUG
      - IPFS_GATEWAY_URL=http://ipfs.dappnode:8080
      - IPFS_HASH=QmSfPFSauovbMzEcvf2a2csoHtfqpViShwEYpuX3fPR8zv
    # command: ["--ipfs-gateway-url", "${IPFS_GATEWAY_URL}", "--ipfs-hash", "${IPFS_HASH}"]
    networks:
      - dncore_network

networks:
  dncore_network:
    external: true
